### Implementing FunkSVD

In this notebook we will take a look at writing our own function that performs FunkSVD, which will follow the steps you saw in the previous video.  If you find that you aren't ready to tackle this task on your own, feel free to skip to the following video where you can watch as I walk through the steps.

To test our algorithm, we will run it on the subset of the data you worked with earlier.  Run the cell below to get started.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse
import svd_tests as t
from time import time
from tqdm import tqdm
%matplotlib inline

# Read in the datasets
movies = pd.read_csv('data/movies_clean.csv')
reviews = pd.read_csv('data/reviews_clean.csv')

del movies['Unnamed: 0']
del reviews['Unnamed: 0']

# Create user-by-item matrix
user_items = reviews[['user_id', 'movie_id', 'rating', 'timestamp']]
user_by_movie = user_items.groupby(['user_id', 'movie_id'])['rating'].max().unstack()

# Create data subset
user_movie_subset = user_by_movie[[73486, 75314,  68646, 99685]].dropna(axis=0)
ratings_mat = np.matrix(user_movie_subset)
print(ratings_mat)

[[10. 10. 10. 10.]
 [10.  4.  9. 10.]
 [ 8.  9. 10.  5.]
 [ 9.  8. 10. 10.]
 [10.  5.  9.  9.]
 [ 6.  4. 10.  6.]
 [ 9.  8. 10.  9.]
 [10.  5.  9.  8.]
 [ 7.  8. 10.  8.]
 [ 9.  5.  9.  7.]
 [ 9.  8. 10.  8.]
 [ 9. 10. 10.  9.]
 [10.  9. 10.  8.]
 [ 5.  8.  5.  8.]
 [10.  8. 10. 10.]
 [ 9.  9. 10. 10.]
 [ 9.  8.  8.  8.]
 [10.  8.  1. 10.]
 [ 5.  6. 10. 10.]
 [ 8.  7. 10.  7.]]


`1.` You will use the **user_movie_subset** matrix to show that your FunkSVD algorithm will converge.  In the below cell, use the comments and document string to assist you as you complete writing your own function to complete FunkSVD.  You may also want to try to complete the function on your own without the assistance of comments.  You may feel free to remove and add to the function in any way that gets you a working solution! 

**Notice:** There isn't a sigma matrix in this version of the matrix factorization.

In [17]:
np.random.rand()

0.29718440668560075

In [3]:
def FunkSVD(ratings_mat, latent_features=4, learning_rate=0.0001, iters=100):
    '''
    This function performs matrix factorization using a basic form of FunkSVD with no regularization
    
    INPUT:
    ratings_mat - (numpy array) a matrix with users as rows, movies as columns, and ratings as values
    latent_features - (int) the number of latent features used
    learning_rate - (float) the learning rate 
    iters - (int) the number of iterations
    
    OUTPUT:
    user_mat - (numpy array) a user by latent feature matrix
    movie_mat - (numpy array) a latent feature by movie matrix
    '''
    
    # Set up useful values to be used through the rest of the function
    n_users = ratings_mat.shape[0]  # number of rows in the matrix
    n_movies = ratings_mat.shape[1]  # number of movies in the matrix
    num_ratings = (1 - np.isnan(ratings_mat)).sum()  # total number of ratings in the matrix
    
    # initialize the user and movie matrices with random values
    # helpful link: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html
    min_rating, max_rating = (1, 10)
    user_mat = np.random.rand(n_users, latent_features)
    movie_mat = np.random.rand(latent_features, n_movies)
    
    # initialize sse at 0 for first iteration
    sse_accum = 0
    
    # header for running results
    print("Optimization Statistics")
    print("Iterations | Mean Squared Error ")
    
    # for each iteration
    mean_iter_time = 0
    for i in range(iters):
        tic = time()
        # update our sse
        old_sse = sse_accum
        sse_accum = 0
        
        # For each user-movie pair
        for u in tqdm(range(n_users)):
            for m in range(n_movies):
                if not np.isnan(ratings_mat[u, m]):
                    # compute the error as the actual minus the dot product of the user and movie latent features
                    error = ratings_mat[u, m] - user_mat[u, :].dot(movie_mat[:, m])

                    # Keep track of the total sum of squared errors for the matrix
                    sse_accum += error**2
                    
                    # update the values in each matrix in the direction of the gradient
                    user_mat[u, :] += learning_rate * 2 * error * movie_mat[:, m]
                    movie_mat[:, m] += learning_rate * 2 * error * user_mat[u, :]
        toc = time()
                    
        # print results for iteration
        iter_time = toc - tic
        mean_iter_time = (mean_iter_time * i + iter_time) / (i + 1)
        eta = mean_iter_time * (iters - i -1)
        print('Iteration {} | {} -- Iter time: {} sec. ETA: {} sec'.format(
            i, sse_accum / num_ratings, iter_time, eta))
        
    return user_mat, movie_mat 

`2.` Try out your function on the **user_movie_subset** dataset.  First try 4 latent features, a learning rate of 0.005, and 10 iterations.  When you take the dot product of the resulting U and V matrices, how does the resulting **user_movie** matrix compare to the original subset of the data?

In [4]:
user_mat, movie_mat = FunkSVD(ratings_mat, latent_features=4, learning_rate=0.005, iters=10)
# use your function with 4 latent features, lr of 0.005 and 10 iterations

100%|██████████| 20/20 [00:00<00:00, 2169.45it/s]

Optimization Statistics
Iterations | Mean Squared Error 
Iteration 0 | 48.758815098045 -- Iter time: 0.009335756301879883 sec. ETA: 0.08402180671691895 sec
Iteration 1 | 19.352768342810617 -- Iter time: 0.0077550411224365234 sec. ETA: 0.06836318969726562 sec
Iteration 2 | 4.912137351014641 -- Iter time: 0.006158113479614258 sec. ETA: 0.05424745877583821 sec
Iteration 3 | 2.899248418635939 -- Iter time: 0.005427122116088867 sec. ETA: 0.0430140495300293 sec
Iteration 4 | 2.7569771186235426 -- Iter time: 0.014972925186157227 sec. ETA: 0.04364895820617676 sec
Iteration 5 | 2.72106994979535 -- Iter time: 0.008913040161132812 sec. ETA: 0.03504133224487305 sec
Iteration 6 | 2.6916651440961648 -- Iter time: 0.008634805679321289 sec. ETA: 0.026227201734270372 sec
Iteration 7 | 2.660425660873849 -- Iter time: 0.009706974029541016 sec. ETA: 0.01772594451904297 sec
Iteration 8 | 2.625481697029229 -- Iter time: 0.012928009033203125 sec. ETA: 0.009314643012152778 sec
Iteration 9 | 2.5859319854110585

In [5]:
#Compare the predicted and actual results
print(np.dot(user_mat, movie_mat))
print(ratings_mat)

[[10.17284711  9.04758688 10.66385153  9.94908877]
 [ 8.62258584  7.43233012  9.31515886  8.63226287]
 [ 7.6210927   6.84469039  8.50138972  7.68117199]
 [ 9.58744304  8.4013951   9.74227532  9.75376647]
 [ 8.67042162  7.58658114  8.7811012   8.54604007]
 [ 6.69634201  5.89278987  7.27924709  6.94380275]
 [ 9.3267497   8.08896863  9.50020664  9.26457908]
 [ 8.13410188  7.16235601  8.68736861  8.17456484]
 [ 8.16971683  7.15742566  9.29591987  8.47200849]
 [ 7.62760315  6.62449824  8.15555185  7.67623551]
 [ 9.18227751  7.99795966  8.8807156   8.95002686]
 [ 9.88615321  8.423767    9.80336953  9.61665618]
 [ 9.10873188  8.07048889  9.76807141  9.3144106 ]
 [ 6.70097932  5.9253199   6.79101468  6.65861496]
 [ 9.7554547   8.55343306 10.24267044  9.7069661 ]
 [ 9.74907532  8.4314104  10.19551076  9.81829753]
 [ 8.33953824  7.27647746  8.7473638   8.20384759]
 [ 7.44870141  6.30987798  6.94095934  7.26948433]
 [ 8.35688065  7.28373021  8.89231803  8.38621354]
 [ 7.87848067  7.00095116  8.82

The algorithm seems to converge and the predicted matrix is similar to the acutal one. In any case the matrix under test has no missing values, so this was an easy case.

`3.` Let's try out the function again on the **user_movie_subset** dataset.  This time we will again use 4 latent features and a learning rate of 0.005.  However, let's bump up the number of iterations to 250.  When you take the dot product of the resulting U and V matrices, how does the resulting **user_movie** matrix compare to the original subset of the data?  What do you notice about your error at the end of the 250 iterations?

In [6]:
user_mat, movie_mat = FunkSVD(ratings_mat, latent_features=4, 
                              learning_rate=0.005, iters=250)
#use your function with 4 latent features, lr of 0.005 and 250 iterations

100%|██████████| 20/20 [00:00<00:00, 2853.85it/s]

Optimization Statistics
Iterations | Mean Squared Error 
Iteration 0 | 44.001898704518446 -- Iter time: 0.008318901062011719 sec. ETA: 2.071406364440918 sec
Iteration 1 | 15.131324867551902 -- Iter time: 0.008056163787841797 sec. ETA: 2.030508041381836 sec
Iteration 2 | 4.115179205576126 -- Iter time: 0.005526065826416016 sec. ETA: 1.8031930923461914 sec
Iteration 3 | 2.8002822170305346 -- Iter time: 0.010019063949584961 sec. ETA: 1.9630919694900513 sec
Iteration 4 | 2.693577996708192 -- Iter time: 0.006443023681640625 sec. ETA: 1.8797976970672607 sec
Iteration 5 | 2.6713434271323253 -- Iter time: 0.013384342193603516 sec. ETA: 2.1044007937113443 sec
Iteration 6 | 2.658877702514063 -- Iter time: 0.009544134140014648 sec. ETA: 2.127697399684361 sec
Iteration 7 | 2.646976996608253 -- Iter time: 0.0057032108306884766 sec. ETA: 2.026595890522003 sec
Iteration 8 | 2.6339690981264194 -- Iter time: 0.00554203987121582 sec. ETA: 1.9423782030741372 sec
Iteration 9 | 2.6196065063578304 -- Iter t


100%|██████████| 20/20 [00:00<00:00, 4356.13it/s]


Iteration 20 | 2.361789099768556 -- Iter time: 0.017410755157470703 sec. ETA: 2.36322393871489 sec
Iteration 21 | 2.3291565342346168 -- Iter time: 0.01517176628112793 sec. ETA: 2.4031886620955034 sec
Iteration 22 | 2.295196884910007 -- Iter time: 0.008558034896850586 sec. ETA: 2.373084254886793 sec
Iteration 23 | 2.25997217053878 -- Iter time: 0.015062093734741211 sec. ETA: 2.4060219327608743 sec
Iteration 24 | 2.223526226737551 -- Iter time: 0.014061212539672852 sec. ETA: 2.4261116981506348 sec
Iteration 25 | 2.185877075044006 -- Iter time: 0.013810873031616211 sec. ETA: 2.441417694091797 sec
Iteration 26 | 2.147011412298075 -- Iter time: 0.010787725448608398 sec. ETA: 2.4295979252567994 sec
Iteration 27 | 2.106882175553292 -- Iter time: 0.007863044738769531 sec. ETA: 2.3946633338928223 sec
Iteration 28 | 2.065409909211117 -- Iter time: 0.01318502426147461 sec. ETA: 2.4021529000380943 sec
Iteration 29 | 2.0224883148366506 -- Iter time: 0.010406017303466797 sec. ETA: 2.387884775797526 

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 36 | 1.6726442791678036 -- Iter time: 0.010590791702270508 sec. ETA: 2.4437569025400525 sec
Iteration 37 | 1.615367008538867 -- Iter time: 0.015117168426513672 sec. ETA: 2.4526142823068717 sec
Iteration 38 | 1.5566505155338437 -- Iter time: 0.012160062789916992 sec. ETA: 2.4442434983375745 sec
Iteration 39 | 1.4967830456342148 -- Iter time: 0.010977983474731445 sec. ETA: 2.429477334022522 sec
Iteration 40 | 1.4360915310119902 -- Iter time: 0.012388229370117188 sec. ETA: 2.4220847734590856 sec
Iteration 41 | 1.3749183731384456 -- Iter time: 0.016299962997436523 sec. ETA: 2.4338267190115794 sec
Iteration 42 | 1.3135965474878606 -- Iter time: 0.014825105667114258 sec. ETA: 2.4371644951576408 sec
Iteration 43 | 1.2524265806450396 -- Iter time: 0.013277053833007812 sec. ETA: 2.432428988543424 sec
Iteration 44 | 1.191658778644904 -- Iter time: 0.013905048370361328 sec. ETA: 2.4301747216118708 sec
Iteration 45 | 1.1314832234543548 -- Iter time: 0.013386011123657227 sec. ETA: 2.42511

100%|██████████| 20/20 [00:00<00:00, 3187.16it/s]


Iteration 51 | 0.7871850571969978 -- Iter time: 0.019972801208496094 sec. ETA: 2.3599544763565063 sec
Iteration 52 | 0.7328757675583091 -- Iter time: 0.01476907730102539 sec. ETA: 2.358629339146164 sec
Iteration 53 | 0.6795960342697573 -- Iter time: 0.015614032745361328 sec. ETA: 2.359873153545238 sec
Iteration 54 | 0.6274792903947752 -- Iter time: 0.011921167373657227 sec. ETA: 2.3474110690030185 sec
Iteration 55 | 0.5766973799146629 -- Iter time: 0.016225099563598633 sec. ETA: 2.349878353731973 sec
Iteration 56 | 0.5274535557224059 -- Iter time: 0.011314868927001953 sec. ETA: 2.3350638966811332 sec
Iteration 57 | 0.4799718173970671 -- Iter time: 0.013590812683105469 sec. ETA: 2.327904273723734 sec
Iteration 58 | 0.434483849297896 -- Iter time: 0.016767024993896484 sec. ETA: 2.3308089587648033 sec
Iteration 59 | 0.3912149129369175 -- Iter time: 0.00865316390991211 sec. ETA: 2.307364026705424 sec
Iteration 60 | 0.3503700322023763 -- Iter time: 0.009764909744262695 sec. ETA: 2.287848660

100%|██████████| 20/20 [00:00<00:00, 4800.62it/s]

Iteration 66 | 0.1626307942992009 -- Iter time: 0.018728017807006836 sec. ETA: 2.2937804620657394 sec
Iteration 67 | 0.14094615797924664 -- Iter time: 0.017921924591064453 sec. ETA: 2.2956659092622647 sec
Iteration 68 | 0.12174780665742706 -- Iter time: 0.016249895095825195 sec. ETA: 2.292591181354246 sec
Iteration 69 | 0.10486409753646238 -- Iter time: 0.011532783508300781 sec. ETA: 2.2770103045872276 sec
Iteration 70 | 0.09010672288660694 -- Iter time: 0.008736133575439453 sec. ETA: 2.2544927496305656 sec
Iteration 71 | 0.07727894053520215 -- Iter time: 0.010901927947998047 sec. ETA: 2.237712336911095 sec
Iteration 72 | 0.0661828044744923 -- Iter time: 0.009334802627563477 sec. ETA: 2.217293236353626 sec
Iteration 73 | 0.056625117970160066 -- Iter time: 0.01784515380859375 sec. ETA: 2.217414546657253 sec
Iteration 74 | 0.04842200249082109 -- Iter time: 0.014009237289428711 sec. ETA: 2.208106279373169 sec
Iteration 75 | 0.04140211411291731 -- Iter time: 0.013122081756591797 sec. ETA: 


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 84 | 0.010542144772998436 -- Iter time: 0.009629964828491211 sec. ETA: 2.028569361742805 sec
Iteration 85 | 0.009124746078877612 -- Iter time: 0.011630058288574219 sec. ETA: 2.01500819450201 sec
Iteration 86 | 0.0079114941254164 -- Iter time: 0.012157201766967773 sec. ETA: 2.002479057202394 sec
Iteration 87 | 0.0068711579753740785 -- Iter time: 0.010873079299926758 sec. ETA: 1.9875944202596492 sec
Iteration 88 | 0.005977443398519665 -- Iter time: 0.01258087158203125 sec. ETA: 1.975889307729314 sec
Iteration 89 | 0.005208225190071776 -- Iter time: 0.009599924087524414 sec. ETA: 1.958865271674262 sec
Iteration 90 | 0.004544886704348507 -- Iter time: 0.011476993560791016 sec. ETA: 1.9452841177091493 sec
Iteration 91 | 0.003971756488173911 -- Iter time: 0.012485027313232422 sec. ETA: 1.9334798947624539 sec
Iteration 92 | 0.003475631031419265 -- Iter time: 0.010499715805053711 sec. ETA: 1.9183094834768644 sec
Iteration 93 | 0.003045372667628068 -- Iter time: 0.00866389274597168 se

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 104 | 0.0007575171172023127 -- Iter time: 0.014345884323120117 sec. ETA: 1.7389572688511439 sec
Iteration 105 | 0.0006701643370564563 -- Iter time: 0.008528947830200195 sec. ETA: 1.722258837717884 sec
Iteration 106 | 0.0005931428256622277 -- Iter time: 0.010095834732055664 sec. ETA: 1.7078071710105254 sec
Iteration 107 | 0.0005251816558865766 -- Iter time: 0.012054920196533203 sec. ETA: 1.6960120024504484 sec
Iteration 108 | 0.0004651753634085516 -- Iter time: 0.010024785995483398 sec. ETA: 1.6815859309030237 sec
Iteration 109 | 0.00041216077076617914 -- Iter time: 0.010308265686035156 sec. ETA: 1.6676006750626997 sec
Iteration 110 | 0.00036529733383658137 -- Iter time: 0.01217508316040039 sec. ETA: 1.6560193976840456 sec
Iteration 111 | 0.0003238504326649654 -- Iter time: 0.010023832321166992 sec. ETA: 1.6417768682752338 sec
Iteration 112 | 0.00028717712920463604 -- Iter time: 0.009505033493041992 sec. ETA: 1.6269800198816622 sec
Iteration 113 | 0.0002547139970513681 -- Iter

100%|██████████| 20/20 [00:00<00:00, 4278.81it/s]


Iteration 124 | 6.876352690430393e-05 -- Iter time: 0.008804082870483398 sec. ETA: 1.4652042388916016 sec
Iteration 125 | 6.108280620519674e-05 -- Iter time: 0.008646249771118164 sec. ETA: 1.450456036461724 sec
Iteration 126 | 5.426336610337895e-05 -- Iter time: 0.012818098068237305 sec. ETA: 1.4398443792748639 sec
Iteration 127 | 4.8207952504613893e-05 -- Iter time: 0.008486747741699219 sec. ETA: 1.4250699281692505 sec
Iteration 128 | 4.283042375525681e-05 -- Iter time: 0.010374069213867188 sec. ETA: 1.4121632391168166 sec
Iteration 129 | 3.805445599479629e-05 -- Iter time: 0.01076197624206543 sec. ETA: 1.3996535814725437 sec
Iteration 130 | 3.3812404040293336e-05 -- Iter time: 0.008713006973266602 sec. ETA: 1.3853093285597007 sec
Iteration 131 | 3.004429824203586e-05 -- Iter time: 0.011058807373046875 sec. ETA: 1.3731474009427156 sec
Iteration 132 | 2.669696036995291e-05 -- Iter time: 0.0058748722076416016 sec. ETA: 1.356441757732764 sec
Iteration 133 | 2.3723223831058017e-05 -- Iter

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 144 | 6.478277303255993e-06 -- Iter time: 0.011792182922363281 sec. ETA: 1.208584588149498 sec
Iteration 145 | 5.757455034913788e-06 -- Iter time: 0.010185003280639648 sec. ETA: 1.196130190810112 sec
Iteration 146 | 5.116837370246285e-06 -- Iter time: 0.010465860366821289 sec. ETA: 1.1839034605999381 sec
Iteration 147 | 4.547494863895501e-06 -- Iter time: 0.012942075729370117 sec. ETA: 1.1734071067861607 sec
Iteration 148 | 4.041493742391312e-06 -- Iter time: 0.00952291488647461 sec. ETA: 1.1605602382813522 sec
Iteration 149 | 3.59178454155269e-06 -- Iter time: 0.009859800338745117 sec. ETA: 1.147982279459635 sec
Iteration 150 | 3.192103268172561e-06 -- Iter time: 0.012856006622314453 sec. ETA: 1.1374047228832116 sec
Iteration 151 | 2.8368836642505718e-06 -- Iter time: 0.00961923599243164 sec. ETA: 1.1247103214263912 sec
Iteration 152 | 2.521179315885548e-06 -- Iter time: 0.008992910385131836 sec. ETA: 1.1116590359631704 sec
Iteration 153 | 2.240594493468879e-06 -- Iter time:

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 167 | 4.2914105342141085e-07 -- Iter time: 0.012865066528320312 sec. ETA: 0.926611903167906 sec
Iteration 168 | 3.8132694863836133e-07 -- Iter time: 0.011925220489501953 sec. ETA: 0.915611350324732 sec
Iteration 169 | 3.3883635072172123e-07 -- Iter time: 0.007013082504272461 sec. ETA: 0.9022883246926696 sec
Iteration 170 | 3.010769552872219e-07 -- Iter time: 0.008643865585327148 sec. ETA: 0.889792502274987 sec
Iteration 171 | 2.6752232189755084e-07 -- Iter time: 0.009842872619628906 sec. ETA: 0.8778852058011428 sec
Iteration 172 | 2.377045524940148e-07 -- Iter time: 0.015102863311767578 sec. ETA: 0.8683429274255827 sec
Iteration 173 | 2.112077837499545e-07 -- Iter time: 0.013375997543334961 sec. ETA: 0.8579824710714403 sec
Iteration 174 | 1.8766240280980421e-07 -- Iter time: 0.011252880096435547 sec. ETA: 0.8466776439121789 sec
Iteration 175 | 1.6673990594653517e-07 -- Iter time: 0.007498025894165039 sec. ETA: 0.8337946615435858 sec
Iteration 176 | 1.4814832865414823e-07 -- I

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 187 | 4.032690507525349e-08 -- Iter time: 0.010725021362304688 sec. ETA: 0.6935459096381004 sec
Iteration 188 | 3.582552502723672e-08 -- Iter time: 0.01285409927368164 sec. ETA: 0.682897994127223 sec
Iteration 189 | 3.182625092004343e-08 -- Iter time: 0.010415792465209961 sec. ETA: 0.6714568640056408 sec
Iteration 190 | 2.8273117106685717e-08 -- Iter time: 0.009079933166503906 sec. ETA: 0.6596138227672476 sec
Iteration 191 | 2.511639109955619e-08 -- Iter time: 0.01576709747314453 sec. ETA: 0.6498196447889009 sec
Iteration 192 | 2.231187990342604e-08 -- Iter time: 0.008021116256713867 sec. ETA: 0.6376758980627504 sec
Iteration 193 | 1.98203134865228e-08 -- Iter time: 0.010740280151367188 sec. ETA: 0.6263595659708238 sec
Iteration 194 | 1.7606796815701726e-08 -- Iter time: 0.01092386245727539 sec. ETA: 0.615100921728672 sec
Iteration 195 | 1.564032283684956e-08 -- Iter time: 0.0072062015533447266 sec. ETA: 0.602821440112834 sec
Iteration 196 | 1.3893339626837598e-08 -- Iter tim

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 207 | 3.773118027100286e-09 -- Iter time: 0.00981903076171875 sec. ETA: 0.46585327616104705 sec
Iteration 208 | 3.351293526438838e-09 -- Iter time: 0.009765148162841797 sec. ETA: 0.4545012900703831 sec
Iteration 209 | 2.976602439944208e-09 -- Iter time: 0.009569168090820312 sec. ETA: 0.44312708718436095 sec
Iteration 210 | 2.643781407065511e-09 -- Iter time: 0.008109092712402344 sec. ETA: 0.4315001218804815 sec
Iteration 211 | 2.3481544285441366e-09 -- Iter time: 0.01131892204284668 sec. ETA: 0.4204816908206579 sec
Iteration 212 | 2.0855673687325607e-09 -- Iter time: 0.009701013565063477 sec. ETA: 0.4091793931146182 sec
Iteration 213 | 1.8523297554379853e-09 -- Iter time: 0.010344982147216797 sec. ETA: 0.398000391844277 sec
Iteration 214 | 1.6451630656917205e-09 -- Iter time: 0.013011932373046875 sec. ETA: 0.387263303579286 sec
Iteration 215 | 1.4611547747165388e-09 -- Iter time: 0.009924173355102539 sec. ETA: 0.3760191158012107 sec
Iteration 216 | 1.2977175266033585e-09 -- I

100%|██████████| 20/20 [00:00<00:00, 6029.33it/s]

Iteration 228 | 3.124265815608036e-10 -- Iter time: 0.012666940689086914 sec. ETA: 0.23017825726338345 sec
Iteration 229 | 2.774556537916606e-10 -- Iter time: 0.005366086959838867 sec. ETA: 0.21873088504957114 sec
Iteration 230 | 2.463976653140129e-10 -- Iter time: 0.012033939361572266 sec. ETA: 0.20788460273247258 sec
Iteration 231 | 2.1881498183636058e-10 -- Iter time: 0.011111974716186523 sec. ETA: 0.19695655025284864 sec
Iteration 232 | 1.9431889118460013e-10 -- Iter time: 0.007990121841430664 sec. ETA: 0.1857991443683149 sec
Iteration 233 | 1.7256413741891133e-10 -- Iter time: 0.009276151657104492 sec. ETA: 0.1747567429501786 sec
Iteration 234 | 1.5324406538866293e-10 -- Iter time: 0.009078025817871094 sec. ETA: 0.16371672711473828 sec
Iteration 235 | 1.3608630731923835e-10 -- Iter time: 0.010142087936401367 sec. ETA: 0.1527564606424105 sec
Iteration 236 | 1.2084895115060888e-10 -- Iter time: 0.008240938186645508 sec. ETA: 0.14169881615457655 sec
Iteration 237 | 1.0731713687481774

In [7]:
#Compare the predicted and actual results
print(np.dot(user_mat, movie_mat))
print(ratings_mat)

[[ 9.99999357  9.99999673  9.99999802 10.0000069 ]
 [ 9.99999696  3.99999852  8.99999914 10.0000033 ]
 [ 8.00000036  9.00000017 10.00000016  4.99999976]
 [ 8.99999536  7.99999783  9.99999874 10.00000497]
 [10.0000042   5.00000214  9.00000139  8.9999957 ]
 [ 6.00000392  4.00000188 10.00000119  5.99999599]
 [ 8.99999736  7.99999867  9.99999925  9.00000291]
 [ 9.99998814  4.99999421  8.99999654  8.00001261]
 [ 6.99999319  7.99999688  9.99999821  8.00000727]
 [ 9.00000494  5.00000273  9.00000177  6.99999487]
 [ 9.00000617  8.00000324 10.00000208  7.99999361]
 [ 9.00000216 10.00000116 10.0000008   8.99999784]
 [ 9.99999028  8.99999532  9.99999722  8.00001036]
 [ 5.00000168  8.00000108  5.00000075  7.99999824]
 [10.00001115  8.00000566 10.00000355  9.99998836]
 [ 9.00000007  9.00000005 10.00000005 10.        ]
 [ 9.00000537  8.00000261  8.00000161  7.99999443]
 [10.00000024  8.00000007  1.00000005  9.99999979]
 [ 4.99999893  5.99999939  9.99999962 10.00000118]
 [ 8.          6.99999991  9.99

The predicted and the actual matrices are basically the same. The error after 250 iterations is zero, for all practical means.

The last time we placed an **np.nan** value into this matrix the entire svd algorithm in python broke.  Let's see if that is still the case using your FunkSVD function.  In the below cell, I have placed a nan into the first cell of your numpy array.  

`4.` Use 4 latent features, a learning rate of 0.005, and 250 iterations.  Are you able to run your SVD without it breaking (something that was not true about the python built in)?  Do you get a prediction for the nan value?  What is your prediction for the missing value? Use the cells below to answer these questions.

In [8]:
# Here we are placing a nan into our original subset matrix
ratings_mat[0, 0] = np.nan
ratings_mat

matrix([[nan, 10., 10., 10.],
        [10.,  4.,  9., 10.],
        [ 8.,  9., 10.,  5.],
        [ 9.,  8., 10., 10.],
        [10.,  5.,  9.,  9.],
        [ 6.,  4., 10.,  6.],
        [ 9.,  8., 10.,  9.],
        [10.,  5.,  9.,  8.],
        [ 7.,  8., 10.,  8.],
        [ 9.,  5.,  9.,  7.],
        [ 9.,  8., 10.,  8.],
        [ 9., 10., 10.,  9.],
        [10.,  9., 10.,  8.],
        [ 5.,  8.,  5.,  8.],
        [10.,  8., 10., 10.],
        [ 9.,  9., 10., 10.],
        [ 9.,  8.,  8.,  8.],
        [10.,  8.,  1., 10.],
        [ 5.,  6., 10., 10.],
        [ 8.,  7., 10.,  7.]])

In [9]:
# run SVD on the matrix with the missing value
user_mat, movie_mat = FunkSVD(ratings_mat, latent_features=4, 
                              learning_rate=0.005, iters=250)
#use your function with 4 latent features, lr of 0.005 and 250 iterations

100%|██████████| 20/20 [00:00<00:00, 6420.67it/s]

Optimization Statistics
Iterations | Mean Squared Error 
Iteration 0 | 42.020098491256505 -- Iter time: 0.0065310001373291016 sec. ETA: 1.6262190341949463 sec
Iteration 1 | 14.90571501980531 -- Iter time: 0.007200002670288086 sec. ETA: 1.7026443481445312 sec
Iteration 2 | 4.288855832498844 -- Iter time: 0.0045680999755859375 sec. ETA: 1.5066261291503906 sec
Iteration 3 | 2.8754430890846017 -- Iter time: 0.006797075271606445 sec. ETA: 1.5434149503707886 sec
Iteration 4 | 2.741064689064605 -- Iter time: 0.010975122451782227 sec. ETA: 1.767493724822998 sec
Iteration 5 | 2.7075536144918786 -- Iter time: 0.016086101531982422 sec. ETA: 2.121067682902018 sec
Iteration 6 | 2.6836563141320875 -- Iter time: 0.006746053695678711 sec. ETA: 2.0447913919176375 sec



  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 7 | 2.6594368763728715 -- Iter time: 0.009907960891723633 sec. ETA: 2.081545352935791 sec
Iteration 8 | 2.6330518998702033 -- Iter time: 0.01913309097290039 sec. ETA: 2.3549584812588162 sec
Iteration 9 | 2.6038482776858447 -- Iter time: 0.012302160263061523 sec. ETA: 2.4059200286865234 sec
Iteration 10 | 2.5713466847732 -- Iter time: 0.014060020446777344 sec. ETA: 2.4835725914348252 sec
Iteration 11 | 2.535102121960849 -- Iter time: 0.007738828659057617 sec. ETA: 2.42056941986084 sec
Iteration 12 | 2.4947165454229667 -- Iter time: 0.013025999069213867 sec. ETA: 2.462457638520461 sec
Iteration 13 | 2.449876432890763 -- Iter time: 0.015049934387207031 sec. ETA: 2.530618735722133 sec
Iteration 14 | 2.400394429295841 -- Iter time: 0.00896596908569336 sec. ETA: 2.4923695723215737 sec
Iteration 15 | 2.346250951988085 -- Iter time: 0.012180805206298828 sec. ETA: 2.504797786474228 sec
Iteration 16 | 2.2876317471676506 -- Iter time: 0.016199827194213867 sec. ETA: 2.569415064419017 sec

100%|██████████| 20/20 [00:00<00:00, 4859.30it/s]

Iteration 17 | 2.2249551287371343 -- Iter time: 0.015063047409057617 sec. ETA: 2.610400835673014 sec
Iteration 18 | 2.158881077074779 -- Iter time: 0.020689964294433594 sec. ETA: 2.713898194463629 sec
Iteration 19 | 2.0902946582471245 -- Iter time: 0.011549949645996094 sec. ETA: 2.6998666524887085 sec
Iteration 20 | 2.0202590152950797 -- Iter time: 0.007685184478759766 sec. ETA: 2.6439271086738225 sec
Iteration 21 | 1.9499385414094281 -- Iter time: 0.013569116592407227 sec. ETA: 2.6533532576127485 sec



  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 22 | 1.8804998347668598 -- Iter time: 0.013646125793457031 sec. ETA: 2.6615398655767026 sec
Iteration 23 | 1.8130046717701749 -- Iter time: 0.009613752365112305 sec. ETA: 2.629935562610626 sec
Iteration 24 | 1.7483130446359163 -- Iter time: 0.008523941040039062 sec. ETA: 2.5902822017669678 sec
Iteration 25 | 1.6870134110474129 -- Iter time: 0.015017986297607422 sec. ETA: 2.6089721092811 sec
Iteration 26 | 1.6293914843121473 -- Iter time: 0.016212940216064453 sec. ETA: 2.6350345699875444 sec
Iteration 27 | 1.5754399469632363 -- Iter time: 0.016225099563598633 sec. ETA: 2.6581737654549733 sec
Iteration 28 | 1.5249024689755577 -- Iter time: 0.010612010955810547 sec. ETA: 2.635822575667809 sec
Iteration 29 | 1.4773392611193676 -- Iter time: 0.0060901641845703125 sec. ETA: 2.5810937881469727 sec
Iteration 30 | 1.4321995656159556 -- Iter time: 0.013839960098266602 sec. ETA: 2.5842515345542663 sec
Iteration 31 | 1.3888886216863752 -- Iter time: 0.008409261703491211 sec. ETA: 2.54935

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 34 | 1.2643272682875906 -- Iter time: 0.011411905288696289 sec. ETA: 2.5356019905635288 sec
Iteration 35 | 1.2230325090399032 -- Iter time: 0.009431123733520508 sec. ETA: 2.509765492545234 sec
Iteration 36 | 1.1812518338113516 -- Iter time: 0.01111292839050293 sec. ETA: 2.4944975118379333 sec
Iteration 37 | 1.1387324006892399 -- Iter time: 0.012952089309692383 sec. ETA: 2.48970880006489 sec
Iteration 38 | 1.095282729340504 -- Iter time: 0.014505147933959961 sec. ETA: 2.492903898923825 sec


100%|██████████| 20/20 [00:00<00:00, 4365.88it/s]


Iteration 39 | 1.0507653714005782 -- Iter time: 0.01591968536376953 sec. ETA: 2.5026403069496155 sec
Iteration 40 | 1.005091371430347 -- Iter time: 0.008154153823852539 sec. ETA: 2.471539927691948 sec
Iteration 41 | 0.9582173489676092 -- Iter time: 0.012171030044555664 sec. ETA: 2.461425327119373 sec
Iteration 42 | 0.9101454931216679 -- Iter time: 0.018559932708740234 sec. ETA: 2.4819709589315018 sec
Iteration 43 | 0.8609262839240686 -- Iter time: 0.011842966079711914 sec. ETA: 2.4692914485931396 sec
Iteration 44 | 0.8106632982138418 -- Iter time: 0.020547151565551758 sec. ETA: 2.4963015185462103 sec
Iteration 45 | 0.7595190128276793 -- Iter time: 0.020576953887939453 sec. ETA: 2.5213760500368867 sec
Iteration 46 | 0.7077201175149779 -- Iter time: 0.010928153991699219 sec. ETA: 2.5028333613213074 sec
Iteration 47 | 0.6555605685336982 -- Iter time: 0.01673293113708496 sec. ETA: 2.509036382039388 sec
Iteration 48 | 0.6034005516094891 -- Iter time: 0.015561819076538086 sec. ETA: 2.5094992

100%|██████████| 20/20 [00:00<00:00, 3748.76it/s]


Iteration 49 | 0.5516597775617378 -- Iter time: 0.017403125762939453 sec. ETA: 2.51668643951416 sec
Iteration 50 | 0.5008041611598842 -- Iter time: 0.011752843856811523 sec. ETA: 2.5008620841830385 sec
Iteration 51 | 0.45132590685020907 -- Iter time: 0.010352849960327148 sec. ETA: 2.4798635794566226 sec
Iteration 52 | 0.40371820870771485 -- Iter time: 0.012559890747070312 sec. ETA: 2.4674703265136144 sec
Iteration 53 | 0.3584469298072305 -- Iter time: 0.010193109512329102 sec. ETA: 2.446480362503617 sec


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 54 | 0.3159224706016338 -- Iter time: 0.01305699348449707 sec. ETA: 2.436036781831221 sec
Iteration 55 | 0.27647531429833155 -- Iter time: 0.01826310157775879 sec. ETA: 2.4435353108814786 sec
Iteration 56 | 0.2403383252041064 -- Iter time: 0.01036214828491211 sec. ETA: 2.4233775724444473 sec
Iteration 57 | 0.2076378365066606 -- Iter time: 0.011785030364990234 sec. ETA: 2.4082678433122306 sec
Iteration 58 | 0.17839414044728932 -- Iter time: 0.006570100784301758 sec. ETA: 2.3763885861736234 sec
Iteration 59 | 0.15253053380541287 -- Iter time: 0.010760068893432617 sec. ETA: 2.3586211999257403 sec
Iteration 60 | 0.12988891115540613 -- Iter time: 0.008384943008422852 sec. ETA: 2.3337245651933016 sec
Iteration 61 | 0.11024925763890162 -- Iter time: 0.00872182846069336 sec. ETA: 2.3103820893072315 sec
Iteration 62 | 0.09335032463312268 -- Iter time: 0.011426925659179688 sec. ETA: 2.2955331764523943 sec
Iteration 63 | 0.0789091751605766 -- Iter time: 0.00885319709777832 sec. ETA: 2.2

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 69 | 0.028762524915754012 -- Iter time: 0.007377147674560547 sec. ETA: 2.1440113612583707 sec
Iteration 70 | 0.02440046810062447 -- Iter time: 0.010206937789916992 sec. ETA: 2.1278035909357205 sec
Iteration 71 | 0.02073414632327599 -- Iter time: 0.00565791130065918 sec. ETA: 2.100516306029426 sec
Iteration 72 | 0.01764881356289989 -- Iter time: 0.011001110076904297 sec. ETA: 2.0867770338711673 sec
Iteration 73 | 0.01504834904934676 -- Iter time: 0.006843090057373047 sec. ETA: 2.0632224211821684 sec
Iteration 74 | 0.012852625120606465 -- Iter time: 0.009251117706298828 sec. ETA: 2.0457321802775064 sec
Iteration 75 | 0.010995060612949742 -- Iter time: 0.006148815155029297 sec. ETA: 2.0213561183527897 sec


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 76 | 0.00942043105453323 -- Iter time: 0.01196432113647461 sec. ETA: 2.010519498354429 sec
Iteration 77 | 0.008082961253004648 -- Iter time: 0.011398792266845703 sec. ETA: 1.998406899281037 sec
Iteration 78 | 0.006944696764620994 -- Iter time: 0.007512092590332031 sec. ETA: 1.9778993884219398 sec
Iteration 79 | 0.005974133939772605 -- Iter time: 0.008044958114624023 sec. ETA: 1.9588491022586823 sec
Iteration 80 | 0.0051450800060997715 -- Iter time: 0.008426189422607422 sec. ETA: 1.9408659611219243 sec
Iteration 81 | 0.0044357119918030105 -- Iter time: 0.009666919708251953 sec. ETA: 1.9256579003682952 sec
Iteration 82 | 0.0038278040016241 -- Iter time: 0.00511479377746582 sec. ETA: 1.9014242643333343 sec
Iteration 83 | 0.0033060949002262307 -- Iter time: 0.011592864990234375 sec. ETA: 1.8904477414630707 sec
Iteration 84 | 0.002857771822414419 -- Iter time: 0.0071070194244384766 sec. ETA: 1.870748898562263 sec
Iteration 85 | 0.0024720484926399303 -- Iter time: 0.028758049011230

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 90 | 0.0012082190284611214 -- Iter time: 0.01627182960510254 sec. ETA: 1.8276526246752056 sec
Iteration 91 | 0.0010486388703873275 -- Iter time: 0.016472816467285156 sec. ETA: 1.8247073785118435 sec
Iteration 92 | 0.0009105331302211014 -- Iter time: 0.013186216354370117 sec. ETA: 1.815922870430895 sec
Iteration 93 | 0.0007909433206549649 -- Iter time: 0.012350797653198242 sec. ETA: 1.8056582694358014 sec


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 94 | 0.0006873319806963608 -- Iter time: 0.008698225021362305 sec. ETA: 1.7893902879012258 sec
Iteration 95 | 0.0005975199089876397 -- Iter time: 0.012003898620605469 sec. ETA: 1.7785828610261283 sec
Iteration 96 | 0.0005196333738178183 -- Iter time: 0.007211923599243164 sec. ETA: 1.7601922885658814 sec
Iteration 97 | 0.00045205958313240715 -- Iter time: 0.010502338409423828 sec. ETA: 1.7471333523185886 sec
Iteration 98 | 0.00039340901877254065 -- Iter time: 0.011940717697143555 sec. ETA: 1.73631995615333 sec
Iteration 99 | 0.000342483495807822 -- Iter time: 0.00883793830871582 sec. ETA: 1.7208298444747925 sec
Iteration 100 | 0.00029824901358091916 -- Iter time: 0.011012077331542969 sec. ETA: 1.7086788522134913 sec
Iteration 101 | 0.0002598126305663387 -- Iter time: 0.009827852249145508 sec. ETA: 1.6948319042430204 sec
Iteration 102 | 0.0002264027287223925 -- Iter time: 0.009658336639404297 sec. ETA: 1.680821066921197 sec
Iteration 103 | 0.00019735214126454661 -- Iter time: 0

100%|██████████| 20/20 [00:00<00:00, 5938.00it/s]

Iteration 109 | 8.715091238560731e-05 -- Iter time: 0.013764142990112305 sec. ETA: 1.5988574461503462 sec
Iteration 110 | 7.613495159643692e-05 -- Iter time: 0.010002851486206055 sec. ETA: 1.585661894566304 sec
Iteration 111 | 6.653203869441636e-05 -- Iter time: 0.008153676986694336 sec. ETA: 1.5702449083328247 sec
Iteration 112 | 5.8158338250061865e-05 -- Iter time: 0.012952804565429688 sec. ETA: 1.5607748875575784 sec



100%|██████████| 20/20 [00:00<00:00, 4047.58it/s]

Iteration 113 | 5.085425796892916e-05 -- Iter time: 0.010722160339355469 sec. ETA: 1.5485826458847314 sec
Iteration 114 | 4.448120834035133e-05 -- Iter time: 0.007730960845947266 sec. ETA: 1.532904562742814 sec
Iteration 115 | 3.8918801751145016e-05 -- Iter time: 0.008927106857299805 sec. ETA: 1.5187452538260098 sec
Iteration 116 | 3.406243038047543e-05 -- Iter time: 0.009675741195678711 sec. ETA: 1.5055263959444487 sec
Iteration 117 | 2.9821170785605318e-05 -- Iter time: 0.011205911636352539 sec. ETA: 1.4940793069742495 sec
Iteration 118 | 2.6115970418002262e-05 -- Iter time: 0.013009071350097656 sec. ETA: 1.4846212623500021 sec
Iteration 119 | 2.287807757175194e-05 -- Iter time: 0.014441967010498047 sec. ETA: 1.4766563375790913 sec
Iteration 120 | 2.0047681625099913e-05 -- Iter time: 0.008462667465209961 sec. ETA: 1.4622097291237066 sec
Iteration 121 | 1.7572735027776254e-05 -- Iter time: 0.011362791061401367 sec. ETA: 1.4509039706871159 sec
Iteration 122 | 1.5407932425981264e-05 -- 


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 128 | 7.044438580701354e-06 -- Iter time: 0.01293182373046875 sec. ETA: 1.36455737897592 sec
Iteration 129 | 6.1891551050256135e-06 -- Iter time: 0.011199235916137695 sec. ETA: 1.3532079549936147 sec
Iteration 130 | 5.4392247341680705e-06 -- Iter time: 0.008355140686035156 sec. ETA: 1.3392772565361197 sec
Iteration 131 | 4.781474096198918e-06 -- Iter time: 0.013343095779418945 sec. ETA: 1.3298899657798537 sec
Iteration 132 | 4.2044018863921875e-06 -- Iter time: 0.009778976440429688 sec. ETA: 1.3173078361310457 sec


100%|██████████| 20/20 [00:00<00:00, 5446.44it/s]


Iteration 133 | 3.6979635527362494e-06 -- Iter time: 0.008022069931030273 sec. ETA: 1.3032466404473604 sec
Iteration 134 | 3.2533840822683347e-06 -- Iter time: 0.010954856872558594 sec. ETA: 1.291773213280572 sec
Iteration 135 | 2.862995175864751e-06 -- Iter time: 0.00848388671875 sec. ETA: 1.2782361577538883 sec
Iteration 136 | 2.5200935949742747e-06 -- Iter time: 0.011595964431762695 sec. ETA: 1.2673397673307545 sec
Iteration 137 | 2.218817892704503e-06 -- Iter time: 0.008804082870483398 sec. ETA: 1.2541673632635588 sec
Iteration 138 | 1.9540411128640925e-06 -- Iter time: 0.00771784782409668 sec. ETA: 1.2401903876297764 sec
Iteration 139 | 1.7212773617593842e-06 -- Iter time: 0.0060961246490478516 sec. ETA: 1.2250286170414517 sec
Iteration 140 | 1.5166004356502035e-06 -- Iter time: 0.009311914443969727 sec. ETA: 1.2124814023362829 sec
Iteration 141 | 1.3365729275738184e-06 -- Iter time: 0.010886192321777344 sec. ETA: 1.2011770933446748 sec
Iteration 142 | 1.1781844457714054e-06 -- It

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 151 | 3.822235803181606e-07 -- Iter time: 0.010782957077026367 sec. ETA: 1.0731441817785565 sec
Iteration 152 | 3.376096008553942e-07 -- Iter time: 0.007400989532470703 sec. ETA: 1.0599434188767975 sec
Iteration 153 | 2.982553266742677e-07 -- Iter time: 0.009000062942504883 sec. ETA: 1.0478148026899858 sec
Iteration 154 | 2.6353339702107854e-07 -- Iter time: 0.0072307586669921875 sec. ETA: 1.034642142634238 sec
Iteration 155 | 2.3289227432250044e-07 -- Iter time: 0.009809255599975586 sec. ETA: 1.0230993704918103 sec


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 156 | 2.0584694719449268e-07 -- Iter time: 0.01367497444152832 sec. ETA: 1.0138685657719897 sec
Iteration 157 | 1.8197079079379639e-07 -- Iter time: 0.011172771453857422 sec. ETA: 1.0031245267843898 sec
Iteration 158 | 1.608884382196242e-07 -- Iter time: 0.013554811477661133 sec. ETA: 0.9937384008611523 sec
Iteration 159 | 1.4226953543187526e-07 -- Iter time: 0.009690284729003906 sec. ETA: 0.9821263700723648 sec
Iteration 160 | 1.2582326849425454e-07 -- Iter time: 0.00972890853881836 sec. ETA: 0.9705595629555839 sec
Iteration 161 | 1.1129356614797219e-07 -- Iter time: 0.014792919158935547 sec. ETA: 0.961766266528471 sec
Iteration 162 | 9.845489309413671e-08 -- Iter time: 0.012473821640014648 sec. ETA: 0.9516615545822799 sec
Iteration 163 | 8.710856012404148e-08 -- Iter time: 0.009313821792602539 sec. ETA: 0.9398708779637405 sec
Iteration 164 | 7.707948662326906e-08 -- Iter time: 0.009025812149047852 sec. ETA: 0.9279618552236845 sec
Iteration 165 | 6.82133591334608e-08 -- Iter

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 171 | 3.284444847382816e-08 -- Iter time: 0.011749982833862305 sec. ETA: 0.8464348122130991 sec
Iteration 172 | 2.9087973895650504e-08 -- Iter time: 0.01106882095336914 sec. ETA: 0.8356797088777397 sec
Iteration 173 | 2.5763474233944878e-08 -- Iter time: 0.006793975830078125 sec. ETA: 0.8230538258607358 sec
Iteration 174 | 2.282093081650621e-08 -- Iter time: 0.010601043701171875 sec. ETA: 0.8121261937277656 sec
Iteration 175 | 2.021616628194393e-08 -- Iter time: 0.009165048599243164 sec. ETA: 0.8005985021591185 sec


100%|██████████| 20/20 [00:00<00:00, 7880.33it/s]

Iteration 176 | 1.7910155381048306e-08 -- Iter time: 0.01595282554626465 sec. ETA: 0.7918969857490668 sec
Iteration 177 | 1.586841807471748e-08 -- Iter time: 0.011256217956542969 sec. ETA: 0.7812142425708556 sec
Iteration 178 | 1.406048496660055e-08 -- Iter time: 0.006189107894897461 sec. ETA: 0.768515232555027 sec
Iteration 179 | 1.245942633443651e-08 -- Iter time: 0.012713909149169922 sec. ETA: 0.7584259774949813 sec
Iteration 180 | 1.1041437093246333e-08 -- Iter time: 0.011050939559936523 sec. ETA: 0.7476737709993815 sec
Iteration 181 | 9.785470961402923e-09 -- Iter time: 0.00677180290222168 sec. ETA: 0.735319483411181 sec
Iteration 182 | 8.672917922868893e-09 -- Iter time: 0.008831024169921875 sec. ETA: 0.7237801291252093 sec
Iteration 183 | 7.68731979627129e-09 -- Iter time: 0.008627176284790039 sec. ETA: 0.7121970938599625 sec
Iteration 184 | 6.814119354050718e-09 -- Iter time: 0.009610891342163086 sec. ETA: 0.7009916434416897 sec
Iteration 185 | 6.040438985794486e-09 -- Iter tim


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 192 | 2.6017511920404992e-09 -- Iter time: 0.01010894775390625 sec. ETA: 0.6127059756165338 sec
Iteration 193 | 2.3071755988220747e-09 -- Iter time: 0.00997781753540039 sec. ETA: 0.601734072891707 sec
Iteration 194 | 2.0460255209317682e-09 -- Iter time: 0.009140968322753906 sec. ETA: 0.5905363315191022 sec
Iteration 195 | 1.8144965955086058e-09 -- Iter time: 0.007025957107543945 sec. ETA: 0.5787768704550604 sec
Iteration 196 | 1.6092192373042141e-09 -- Iter time: 0.011063814163208008 sec. ETA: 0.5681517922938775 sec
Iteration 197 | 1.4272086830233247e-09 -- Iter time: 0.004785776138305664 sec. ETA: 0.5558735047928007 sec


100%|██████████| 20/20 [00:00<00:00, 3644.84it/s]


Iteration 198 | 1.2658208147697643e-09 -- Iter time: 0.016051054000854492 sec. ETA: 0.5465576001747167 sec
Iteration 199 | 1.1227130887726441e-09 -- Iter time: 0.012604951858520508 sec. ETA: 0.5363128185272215 sec
Iteration 200 | 9.958099741625275e-10 -- Iter time: 0.010360002517700195 sec. ETA: 0.5254972763915559 sec
Iteration 201 | 8.832723771733469e-10 -- Iter time: 0.008198022842407227 sec. ETA: 0.5141725068045133 sec
Iteration 202 | 7.834705876466118e-10 -- Iter time: 0.015028953552246094 sec. ETA: 0.5044600881379224 sec
Iteration 203 | 6.94960338731226e-10 -- Iter time: 0.007898807525634766 sec. ETA: 0.4930877685546873 sec
Iteration 204 | 6.164616193870691e-10 -- Iter time: 0.011819124221801758 sec. ETA: 0.4826098942175142 sec
Iteration 205 | 5.468399202998869e-10 -- Iter time: 0.015313148498535156 sec. ETA: 0.4728652944842587 sec
Iteration 206 | 4.850896323770574e-10 -- Iter time: 0.013740062713623047 sec. ETA: 0.4627401160733134 sec
Iteration 207 | 4.3031934871854117e-10 -- Ite

  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 211 | 2.665187737978868e-10 -- Iter time: 0.009139776229858398 sec. ETA: 0.40866505200008163 sec
Iteration 212 | 2.36442287937524e-10 -- Iter time: 0.010833978652954102 sec. ETA: 0.3979245418673948 sec
Iteration 213 | 2.0976204605658912e-10 -- Iter time: 0.010807991027832031 sec. ETA: 0.3871787864471149 sec
Iteration 214 | 1.8609413678769167e-10 -- Iter time: 0.011489629745483398 sec. ETA: 0.3765434165333591 sec
Iteration 215 | 1.6509811667524563e-10 -- Iter time: 0.011349916458129883 sec. ETA: 0.3658781449000039 sec


  0%|          | 0/20 [00:00<?, ?it/s]

Iteration 216 | 1.464720769439912e-10 -- Iter time: 0.011405229568481445 sec. ETA: 0.3552149748472573 sec
Iteration 217 | 1.2994827208367652e-10 -- Iter time: 0.009839773178100586 sec. ETA: 0.34431520514531955 sec
Iteration 218 | 1.1528924578935117e-10 -- Iter time: 0.009954214096069336 sec. ETA: 0.33344131517628 sec
Iteration 219 | 1.0228439758162068e-10 -- Iter time: 0.008347272872924805 sec. ETA: 0.3223566575483841 sec
Iteration 220 | 9.074693968560952e-11 -- Iter time: 0.010317802429199219 sec. ETA: 0.3115553489098181 sec
Iteration 221 | 8.051119965646584e-11 -- Iter time: 0.006088972091674805 sec. ETA: 0.30022503019453156 sec
Iteration 222 | 7.143022937598952e-11 -- Iter time: 0.012878894805908203 sec. ETA: 0.28976381733813084 sec
Iteration 223 | 6.337368542899504e-11 -- Iter time: 0.010308980941772461 sec. ETA: 0.2789827244622366 sec
Iteration 224 | 5.622594997660082e-11 -- Iter time: 0.012918949127197266 sec. ETA: 0.26849582460191507 sec
Iteration 225 | 4.9884464787252254e-11 --

100%|██████████| 20/20 [00:00<00:00, 4316.02it/s]

Iteration 231 | 2.4329791348312137e-11 -- Iter time: 0.013098001480102539 sec. ETA: 0.19289416896885833 sec
Iteration 232 | 2.158567936717402e-11 -- Iter time: 0.011469125747680664 sec. ETA: 0.18223275033189495 sec
Iteration 233 | 1.9151030930564075e-11 -- Iter time: 0.011012077331542969 sec. ETA: 0.17153317704159984 sec
Iteration 234 | 1.699094502453869e-11 -- Iter time: 0.009922027587890625 sec. ETA: 0.16076136649923115 sec
Iteration 235 | 1.507445788126229e-11 -- Iter time: 0.006823062896728516 sec. ETA: 0.1498129206188654 sec



100%|██████████| 20/20 [00:00<00:00, 7079.59it/s]

Iteration 236 | 1.3374098559521004e-11 -- Iter time: 0.010473012924194336 sec. ETA: 0.139099496326366 sec
Iteration 237 | 1.1865494692665207e-11 -- Iter time: 0.007253170013427734 sec. ETA: 0.1282257472767549 sec
Iteration 238 | 1.0527022824148942e-11 -- Iter time: 0.009229183197021484 sec. ETA: 0.117473242173135 sec
Iteration 239 | 9.339498208825833e-12 -- Iter time: 0.012717008590698242 sec. ETA: 0.1068787574768066 sec
Iteration 240 | 8.285899665768915e-12 -- Iter time: 0.007941007614135742 sec. ETA: 0.0960883015913587 sec
Iteration 241 | 7.351125485154125e-12 -- Iter time: 0.01112508773803711 sec. ETA: 0.08542665371224897 sec
Iteration 242 | 6.521776907722692e-12 -- Iter time: 0.009529829025268555 sec. ETA: 0.07471523755862386 sec
Iteration 243 | 5.7859660351408526e-12 -- Iter time: 0.00862884521484375 sec. ETA: 0.06399135120579452 sec
Iteration 244 | 5.133145423824163e-12 -- Iter time: 0.005609035491943359 sec. ETA: 0.053222938459746676 sec
Iteration 245 | 4.553956908937936e-12 -- 

In [10]:
# Run this cell to see if you were able to predict for the missing value
preds = np.dot(user_mat, movie_mat)
print("The predicted value for the missing rating is {}:".format(preds[0,0]))
print()
print("The actual value for the missing rating is {}:".format(ratings_mat[0,0]))
print()
assert np.isnan(preds[0,0]) == False
print("That's right! You just predicted a rating for a user-movie pair that was never rated!")
print("But if you look in the original matrix, this was actually a value of 10. Not bad!")

The predicted value for the missing rating is 10.328867452974876:

The actual value for the missing rating is nan:

That's right! You just predicted a rating for a user-movie pair that was never rated!
But if you look in the original matrix, this was actually a value of 10. Not bad!


Now let's extend this to a more realistic example. Unfortunately, running this function on your entire user-movie matrix is still not something you likely want to do on your local machine.  However, we can see how well this example extends to 1000 users.  In the above portion, you were using a very small subset of data with no missing values.

`5.` Given the size of this matrix, this will take quite a bit of time.  Consider the following hyperparameters: 4 latent features, 0.005 learning rate, and 20 iterations.  Grab a snack, take a walk, and this should be done running in a bit.

In [11]:
# Setting up a matrix of the first 1000 users with movie ratings
first_1000_users = np.matrix(user_by_movie.head(1000))

# perform funkSVD on the matrix of the top 1000 users
user_mat, movie_mat = FunkSVD(first_1000_users, latent_features=4, 
                              learning_rate=0.005, iters=20)
#fit to 1000 users with 4 latent features, lr of 0.005, and 20 iterations

  0%|          | 2/1000 [00:00<01:28, 11.33it/s]

Optimization Statistics
Iterations | Mean Squared Error 


  0%|          | 2/1000 [00:00<01:27, 11.46it/s]

Iteration 0 | 0.008045903269022613 -- Iter time: 85.91714286804199 sec. ETA: 1632.4257144927979 sec


  0%|          | 2/1000 [00:00<01:31, 10.92it/s]

Iteration 1 | 0.0037459848263669865 -- Iter time: 86.02216410636902 sec. ETA: 1547.453762769699 sec


  0%|          | 1/1000 [00:00<01:41,  9.84it/s]

Iteration 2 | 0.0025778793429333986 -- Iter time: 85.78318905830383 sec. ETA: 1460.4274775187173 sec


  0%|          | 2/1000 [00:00<01:32, 10.84it/s]

Iteration 3 | 0.001988378140465925 -- Iter time: 95.45509505271912 sec. ETA: 1412.7103643417358 sec


  0%|          | 1/1000 [00:00<01:40,  9.95it/s]

Iteration 4 | 0.0016161881272912688 -- Iter time: 91.90532922744751 sec. ETA: 1335.2487609386444 sec


  0%|          | 1/1000 [00:00<01:44,  9.56it/s]

Iteration 5 | 0.0013565158653557157 -- Iter time: 99.37051892280579 sec. ETA: 1270.3913582166037 sec


  0%|          | 2/1000 [00:00<01:17, 12.85it/s]

Iteration 6 | 0.0011641843729683883 -- Iter time: 94.89393186569214 sec. ETA: 1187.3594034739904 sec


  0%|          | 2/1000 [00:00<01:20, 12.41it/s]

Iteration 7 | 0.0010159580196583905 -- Iter time: 83.01117897033691 sec. ETA: 1083.5378251075745 sec


  0%|          | 2/1000 [00:00<01:24, 11.85it/s]

Iteration 8 | 0.0008984618573871275 -- Iter time: 91.44409823417664 sec. ETA: 994.6476812627582 sec


  0%|          | 2/1000 [00:00<01:21, 12.21it/s]

Iteration 9 | 0.0008033413373328323 -- Iter time: 85.03187704086304 sec. ETA: 898.834525346756 sec


  0%|          | 2/1000 [00:00<01:29, 11.19it/s]

Iteration 10 | 0.0007250611369887763 -- Iter time: 87.81064009666443 sec. ETA: 807.2551353627986 sec


  0%|          | 1/1000 [00:00<02:07,  7.86it/s]

Iteration 11 | 0.0006597876650450508 -- Iter time: 85.65210008621216 sec. ETA: 714.8648436864218 sec


  0%|          | 2/1000 [00:00<01:16, 13.11it/s]

Iteration 12 | 0.0006047672748289016 -- Iter time: 83.588534116745 sec. ETA: 622.4000459634341 sec


  0%|          | 2/1000 [00:00<01:19, 12.55it/s]

Iteration 13 | 0.0005579579631032647 -- Iter time: 85.56338310241699 sec. ETA: 532.0496497494834 sec


  0%|          | 2/1000 [00:00<01:36, 10.39it/s]

Iteration 14 | 0.0005178038194751636 -- Iter time: 86.95697498321533 sec. ETA: 442.8020525773366 sec


  0%|          | 2/1000 [00:00<01:28, 11.30it/s]

Iteration 15 | 0.0004830944858806186 -- Iter time: 86.0358579158783 sec. ETA: 353.61050391197205 sec


  0%|          | 2/1000 [00:00<01:31, 10.90it/s]

Iteration 16 | 0.00045287542991097486 -- Iter time: 87.46501088142395 sec. ETA: 265.0424164463492 sec


  0%|          | 2/1000 [00:00<01:29, 11.13it/s]

Iteration 17 | 0.00042638783679579473 -- Iter time: 86.44891905784607 sec. ETA: 176.4839939541287 sec


  0%|          | 1/1000 [00:00<01:51,  8.96it/s]

Iteration 18 | 0.0004030255592360763 -- Iter time: 87.84607791900635 sec. ETA: 88.22115913190339 sec


100%|██████████| 1000/1000 [01:24<00:00, 11.88it/s]

Iteration 19 | 0.0003823023166040969 -- Iter time: 84.17219424247742 sec. ETA: 0.0 sec


`6.` Now that you have a set of predictions for each user-movie pair,  let's answer a few questions about your results. Provide the correct values for each of the variables below, and check your solutions using the tests below.

In [25]:
preds = np.dot(user_mat, movie_mat)

In [26]:
np.isnan(preds).sum()

0

In [24]:
(1 - np.isnan(preds)).sum()

31245000

In [27]:
# Replace each of the comments below with the correct values
num_ratings = (1 - np.isnan(first_1000_users)).sum()
# How many actual ratings exist in first_1000_users
print("The number of actual ratings in the first_1000_users is {}.".format(num_ratings))
print()


ratings_for_missing = (1 - np.isnan(preds)).sum() - num_ratings
# How many ratings did we make for user-movie pairs that didn't actually have ratings
print("The number of ratings made for user-movie pairs that didn't have ratings is {}".format(ratings_for_missing))

The number of actual ratings in the first_1000_users is 10852.

The number of ratings made for user-movie pairs that didn't have ratings is 31234148


In [28]:
# Test your results against the solution
assert num_ratings == 10852, "Oops!  The number of actual ratings doesn't quite look right."
assert ratings_for_missing == 31234148, "Oops!  The number of movie-user pairs that you made ratings for that didn't actually have ratings doesn't look right."

# Make sure you made predictions on all the missing user-movie pairs
preds = np.dot(user_mat, movie_mat)
assert np.isnan(preds).sum() == 0
print("Nice job!  Looks like you have predictions made for all the missing user-movie pairs! But I still have one question... How good are they?")

Nice job!  Looks like you have predictions made for all the missing user-movie pairs! But I still have one question... How good are they?
